<aside class="flyout l-flyout noindex hidden-print collapse hidden-lg-up" id="flyout-menu">
  <form class="form-search " role="search" action="" method="get" name="searchform">
    <input type="text" class="form-control" placeholder="" name="k" >
    <button type="submit" class="btn btn-primary">
      <i class="material-icons">search</i>
    </button>
  </form>  <nav class="nav nav-main">
    <ul>
    </ul>  </nav>
  <nav class="nav nav-service">
    <ul>
    </ul>  </nav>
  <div class="share">
    <span></span>
  </div></aside>