tabWidth: 2
useTabs: false
printWidth: 120 # max amount of chars on 1 line
bracketSpacing: true # reformat {prop: 'value'} to { prop: 'value' }
endOfLine: lf
semi: true # add semicolons to end of line
trailingComma: none
singleQuote: true
overrides:
  - files: '*.vue'
    options:
      parser: 'vue'
  - files: '*.js'
    options:
      parser: 'babel'