<nav class="global-header noindex hidden-print">
  <div class="container">
    <a class="navbar-brand" href="https://www.kuleuven.be">
    <img class="logo" alt="logo" src="https://stijl.kuleuven.be/releases/latest/img/svg/logo.svg" width="157" height="56"/></a>
    <div class="controls">
      <form class="form-search hidden-md-down" role="search" action="" method="get" name="searchform">
        <input type="text" class="form-control" placeholder="Zoeken in KU Leuven" name="k" id="words">
        <button type="submit" class="btn btn-primary">
          <i class="material-icons">search</i>
        </button>
      </form>
      <a href="#" class="btn-toggle hidden-md-down" role="button"
         aria-expanded="false"
         aria-controls="kuleuven-menu"
         data-toggle="collapse" data-target="#kuleuven-menu">Info
         <span class="lines"></span>
      </a>
         
      <a href="#"
         class="btn-toggle hidden-lg-up js-flyout-toggle flyout-toggle collapsed"
         role="button" aria-expanded="false"
         aria-controls="flyout-menu"
         data-toggle="collapse" data-target="#flyout-menu">Info
         <span class="arrow"></span>
      </a>
    </div>
  </div>

  <div class="container hidden-md-down">
    <div class="nav navbar-nav navbar-collapse collapse" id="kuleuven-menu" role="navigation" aria-expanded="false">
      <nav class="nav-main pull-lg-left">
        <ul>
            <li><a href="https://www.kuleuven.be/onderzoek/">Onderzoek</a></li>
            <li><a href="https://www.kuleuven.be/studeren/">Studeren</a></li>
            <li><a href="https://www.kuleuven.be/overons/">Over KU Leuven</a></li>
        </ul>      </nav>
      <nav class="nav-service pull-lg-right">
        <ul>
            <li class="dropdown">
              <a href="#" id="a-z-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                A-Z
                <i class="material-icons">keyboard_arrow_down</i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="a-z-menu">
                <li><a href="https://bib.kuleuven.be/">Bibliotheken</a></li>
                <li><a href="https://www.kuleuven.be/campus">Campussen</a></li>
                <li><a href="https://admin.kuleuven.be/">Diensten</a></li>
                <li><a href="https://www.kuleuven.be/onderzoek/onderzoekstructuur.html">Departementen</a></li>
                <li><a href="https://www.kuleuven.be/kuleuven/faculteiten">Faculteiten</a></li>
                <li><a href="https://www.kuleuven.be/wieiswie">Personeelsleden</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" id="info-voor-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Info voor
                <i class="material-icons">keyboard_arrow_down</i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="info-voor-menu">
                <li><a href="https://www.kuleuven.be/toekomstigestudenten/">Toekomstige student</a></li>
                <li><a href="https://www.kuleuven.be/studenten/">Student</a></li>
                <li><a href="https://www.kuleuven.be/personeel/jobsite/">Sollicitant</a></li>
                <li><a href="https://admin.kuleuven.be/intranet/">Personeelslid</a></li>
                <li><a href="https://alum.kuleuven.be/">Alumnus</a></li>
                <li><a href="https://www.kuleuven.be/onderzoek/overheid/">Overheid, bedrijf en maatschappij</a></li>
                <li><a href="https://www.kuleuven.be/pers/">Pers</a></li>
                <li><a href="https://www.kuleuven.be/mecenaat/">Schenker</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" id="interne-tools-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Interne tools
                <i class="material-icons">keyboard_arrow_down</i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="interne-tools-menu">
                <li><a href="https://toledo.kuleuven.be/">Toledo</a></li>
                <li><a href="https://www.kuleuven.be/sapredir/kuloket">KU Loket</a></li>
                <li><a href="https://webmail.kuleuven.be/">Webmail</a></li>
                <li><a href="https://admin.kuleuven.be/intranet/">Intranet</a></li>
                <li><a href="https://www.kuleuven.be/wieiswie">Wie-is-wie</a></li>
                <li><a href="https://www.kuleuven.be/wieiswie/nl/unit/50000050">Organigram</a></li>
              </ul>
            </li>
            <li><a href="https://nieuws.kuleuven.be/">Nieuws</a></li>
            <li><a href="https://www.kuleuven.be/personeel/jobsite/">Jobs</a></li>
            <li><a href="https://www.kuleuven.be/kuleuven/contact">Contact</a></li>
        </ul>      </nav>
    </div>
  </div>
</nav>