<nav class="global-header noindex hidden-print">
  <div class="container">
    <a class="navbar-brand" href="https://www.kuleuven.be">
    <img class="logo" alt="logo" src="https://stijl.kuleuven.be/releases/latest/img/svg/logo.svg" width="157" height="56"/></a>
    <div class="controls">
      <form class="form-search hidden-md-down" role="search" action="" method="get" name="searchform">
        <input type="text" class="form-control" placeholder="Search in KU Leuven" name="k" id="words">
        <button type="submit" class="btn btn-primary">
          <i class="material-icons">search</i>
        </button>
      </form>
      <a href="#" class="btn-toggle hidden-md-down" role="button"
         aria-expanded="false"
         aria-controls="kuleuven-menu"
         data-toggle="collapse" data-target="#kuleuven-menu">Info
         <span class="lines"></span>
      </a>
         
      <a href="#"
         class="btn-toggle hidden-lg-up js-flyout-toggle flyout-toggle collapsed"
         role="button" aria-expanded="false"
         aria-controls="flyout-menu"
         data-toggle="collapse" data-target="#flyout-menu">Info
         <span class="arrow"></span>
      </a>
    </div>
  </div>

  <div class="container hidden-md-down">
    <div class="nav navbar-nav navbar-collapse collapse" id="kuleuven-menu" role="navigation" aria-expanded="false">
      <nav class="nav-main pull-lg-left">
        <ul>
            <li><a href="https://www.kuleuven.be/research/">Research</a></li>
            <li><a href="https://www.kuleuven.be/english/study/">Study</a></li>
            <li><a href="https://www.kuleuven.be/english/about-kuleuven/">About KU Leuven</a></li>
        </ul>      </nav>
      <nav class="nav-service pull-lg-right">
        <ul>
            <li class="dropdown">
              <a href="#" id="a-z-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                A-Z
                <i class="material-icons">keyboard_arrow_down</i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="a-z-menu">
                <li><a href="https://www.kuleuven.be/english/faculties_schools">Faculties</a></li>
                <li><a href="https://bib.kuleuven.be/english/">Libraries</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="https://www.kuleuven.be/admissions/" id="admissions-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Admissions
                <i class="material-icons">keyboard_arrow_down</i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="admissions-menu">
                <li><a href="https://www.kuleuven.be/english/application/">How to apply</a></li>
                <li><a href="https://www.kuleuven.be/english/international/funding/">Scholarships</a></li>
                <li><a href="https://www.kuleuven.be/english/admissions/degree_seeking">Degree-seeking students</a></li>
                <li><a href="https://www.kuleuven.be/english/admissions/non_degree_seeking">Non-degree-seeking students</a></li>
                <li><a href="https://www.kuleuven.be/research/phd/">Doctoral students</a></li>
                <li><a href="https://www.kuleuven.be/english/admissions/researcher">Researchers</a></li>
                <li><a href="https://www.kuleuven.be/admissions/vis_scholar/">Short-term study visits</a></li>
                <li><a href="https://admin.kuleuven.be/personeel/english/international_staff/">Prepare your stay</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" id="info-for-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Info for
                <i class="material-icons">keyboard_arrow_down</i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="info-for-menu">
                <li><a href="https://www.kuleuven.be/english/prospective-students">Prospective students</a></li>
                <li><a href="https://www.kuleuven.be/english/education/student">Student</a></li>
                <li><a href="https://www.kuleuven.be/personeel/jobsite/en/index">Job applicant</a></li>
                <li><a href="https://admin.kuleuven.be/intranet/english/index.html">Staff</a></li>
                <li><a href="https://alum.kuleuven.be/eng">Alumnus</a></li>
                <li><a href="https://www.kuleuven.be/english/research/industry/index">Impact on society, policy and business</a></li>
                <li><a href="https://www.kuleuven.be/mediaresources/">Press</a></li>
                <li><a href="https://www.kuleuven.be/mecenaat/en">Donors</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" id="internal-tools-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Internal tools
                <i class="material-icons">keyboard_arrow_down</i>
              </a>
              <ul class="dropdown-menu" aria-labelledby="internal-tools-menu">
                <li><a href="https://toledo.kuleuven.be/english/">Toledo</a></li>
                <li><a href="https://www.kuleuven.be/sapredir/kuloket">KU Loket</a></li>
                <li><a href="https://webmail.kuleuven.be/">Webmail</a></li>
                <li><a href="https://admin.kuleuven.be/intranet/english">Intranet</a></li>
                <li><a href="https://www.kuleuven.be/wieiswie/en/person">Who&#x27;s who</a></li>
                <li><a href="https://www.kuleuven.be/wieiswie/en/unit/50000050">Organisational chart</a></li>
              </ul>
            </li>
            <li><a href="https://nieuws.kuleuven.be/en">News</a></li>
            <li><a href="https://www.kuleuven.be/personeel/jobsite/en/">Jobs</a></li>
            <li><a href="https://www.kuleuven.be/english/contact">Contact</a></li>
        </ul>      </nav>
    </div>
  </div>
</nav>