<!-- GLOBAL HEADER -->
<!-- https://stijl.kuleuven.be/2016/includes/kulak/header.en.inc -->
<nav class="global-header noindex kulak hidden-print">
    <div class="container">
        <a class="navbar-brand" href="https://www.kuleuven-kulak.be/en/"><img class="logo" alt="logo"
                                              src="https://stijl.kuleuven.be/2016/img/svg/logo_kulak.svg"
                                              width="210" height="44"/></a>
    <div class="controls">
        <form class="form-search hidden-md-down" role="search"
              action="//search.kuleuven.be/en/Pages/results.aspx" method="get"
              name="searchform">
        <input class="form-control" type="text"
               placeholder="Search in KU Leuven" name="k"
               id="words">
        <button class="btn btn-primary" type="submit"><i class="material-icons">search</i>
        </button>
        </form>

        <a href="#" class="btn-toggle hidden-md-down" role="button"
           aria-expanded="false"
           aria-controls="kuleuven-menu"
           data-toggle="collapse" data-target="#kuleuven-menu">Info <span
                class="lines"></span></a>

        <a href="#"
           class="btn-toggle hidden-lg-up js-flyout-toggle flyout-toggle collapsed"
           role="button"
           aria-expanded="false"
           aria-controls="flyout-menu"
           data-toggle="collapse" data-target="#flyout-menu">Info <span
                class="arrow"></span></a>
    </div>
    </div>

    <div class="container hidden-md-down">
        <div class="nav navbar-nav navbar-collapse collapse" id="kuleuven-menu" role="navigation"
             aria-expanded="false">
        <nav class="nav-main pull-lg-left">
            <ul>
                <li><a href="https://www.kuleuven-kulak.be/en/research/">Research</a>
                </li>
                <li><a href="https://www.kuleuven-kulak.be/en/education/">Education</a>
                </li>
                <li><a href="https://www.kuleuven-kulak.be/en/about-kulak">About
                    KULAK</a></li>
            </ul>
        </nav>
        <nav class="nav-service pull-lg-right">
        <ul>
            <li class="dropdown">
                <a href="https://www.kuleuven.be/admissions/" data-toggle="dropdown">Information for <i
                        class="material-icons">keyboard_arrow_down</i></a>
                <ul class="dropdown-menu">
                    <li><a
                        href="https://www.kuleuven-kulak.be/en/education/studying-at-kulak/studying-at-kulak">Student</a>
                    </li>
                    <li><a
                        href="https://www.kuleuven-kulak.be/en/research">Researchers</a>
                    </li>
                    <li><a href="https://www.kuleuven-kulak.be/en/staff/">Staff</a>
                    </li>
                    <li><a href="https://www.kuleuven.be/personeel/jobsite/en/">Job
                        Applicants</a></li>
                    <li><a href="https://www.kuleuven-kulak.be/en/companies/">Industry
                        and Society</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="https://www.kuleuven.be/english/living"
                   data-toggle="dropdown">Internal tools <i class="material-icons">
                  keyboard_arrow_down</i></a>
                <ul class="dropdown-menu">
                    <li><a href="https://webmail.kuleuven.be/">Webmail</a></li>
                    <li><a href="https://www.kuleuven.be/sapredir/kuloket">KU&nbsp;Loket</a>
                    </li>
                    <li><a href="https://www.kuleuven.be/wieiswie/en/person">Who's
                        who</a></li>
                </ul>
            </li>
            <li><a href="https://www.kuleuven-kulak.be/en/library/">Library</a></li>
            <li><a href="https://www.kuleuven-kulak.be/en/news/">News</a></li>
            <li><a href="https://www.kuleuven-kulak.be/en/about-kulak/contact/">Contact</a></li>
            <li><a href="https://www.kuleuven.be/english/">KU&nbsp;Leuven</a></li>
        </ul>
        </nav>
      </div>
    </div>
</nav>
<!-- END GLOBAL HEADER -->
