<!-- GLOBAL HEADER -->
<!-- https://stijl.kuleuven.be/2016/includes/kulak/header.nl.inc -->
<nav class="global-header noindex kulak hidden-print">
    <div class="container">
    <a class="navbar-brand" href="https://www.kuleuven-kulak.be/"><img class="logo" alt="logo"
                                          src="https://stijl.kuleuven.be/2016/img/svg/logo_kulak.svg"
                                          width="210" height="44"/></a>
    <div class="controls">
        <form class="form-search hidden-md-down" role="search"
              action="//search.kuleuven.be/Paginas/results.aspx" method="get"
              name="searchform">
        <input class="form-control" type="text" 
               placeholder="Zoeken in KU Leuven" name="k"
               id="words">
        <button class="btn btn-primary" type="submit"><i class="material-icons">search</i>
        </button>
        </form>
        
        <a href="#" class="btn-toggle hidden-md-down" role="button"
           aria-expanded="false"
           aria-controls="kuleuven-menu"
           data-toggle="collapse" data-target="#kuleuven-menu">Info <span
                class="lines"></span></a>

        <a href="#"
           class="btn-toggle hidden-lg-up js-flyout-toggle flyout-toggle collapsed"
           role="button" aria-expanded="false"
           aria-controls="flyout-menu"
           data-toggle="collapse" data-target="#flyout-menu">Info <span
                class="arrow"></span></a>
    </div>
    </div>

    <div class="container hidden-md-down">
        <div class="nav navbar-nav navbar-collapse collapse" id="kuleuven-menu" role="navigation"
             aria-expanded="false">
            <nav class="nav-main pull-lg-left">
                <ul>
                    <li><a href="https://www.kuleuven-kulak.be/nl/onderzoek/">Onderzoek</a></li>
                    <li><a href="https://www.kuleuven-kulak.be/nl/studeren/">Studeren</a></li>
                    <li><a href="https://www.kuleuven-kulak.be/nl/over-kulak/">Over KULAK</a></li>
                </ul>
            </nav>
            <nav class="nav-service pull-lg-right">
                <ul>
                    <li class="dropdown">
                        <a href="#" id="a-z-menu" data-toggle="dropdown"
                          aria-haspopup="true" aria-expanded="false">A-Z <i class="material-icons">
                            keyboard_arrow_down</i></a>
                        <ul class="dropdown-menu" aria-labelledby="a-z-menu">
                            <li><a href="https://www.kuleuven-kulak.be/nl/agenda/">Agenda</a>
                            </li>
                            <li><a href="https://www.kuleuven-kulak.be/nl/bibliotheek">Bibliotheek</a>
                            </li>
                            <li><a href="https://www.kuleuven-kulak.be/nl/diensten-en-raden">Diensten</a>
                            </li>
                            <li><a href="https://www.kuleuven-kulak.be/nl/faculteiten/">Faculteiten</a>
                            </li>
                            <li><a href="https://www.kuleuven-kulak.be/permanente-vorming/">Permanente
                              vorming</a></li>
                            <li><a href="https://www.kuleuven.be/wieiswie/">Personeelsleden</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" id="info-voor-menu" data-toggle="dropdown"
                          aria-haspopup="true" aria-expanded="false">Info voor <i
                            class="material-icons">keyboard_arrow_down</i></a>
                        <ul class="dropdown-menu" aria-labelledby="info-voor-menu">
                          <li><a
                              href="https://www.kuleuven-kulak.be/nl/toekomstige-studenten/">Toekomstige
                              student</a></li>
                          <li><a
                              href="https://www.kuleuven-kulak.be/nl/studenten/">Student</a>
                          </li>
                          <li><a href="https://www.kuleuven-kulak.be/nl/onderzoek/">Onderzoeker</a>
                          </li>
                          <li><a href="https://www.kuleuven-kulak.be/nl/personeel/">Personeelslid</a>
                          </li>
                          <li><a
                              href="https://www.kuleuven-kulak.be/nl/personeel/vacatures/">Sollicitant</a>
                          </li>
                          <li><a
                              href="https://www.kuleuven-kulak.be/nl/over-kulak/kulak-concept/">Schenker</a>
                          </li>
                          <li><a href="https://www.kuleuven-kulak.be/nl/pers/">Bedrijven en
                              professionals</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" id="interne-tools-menu" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">Interne tools <i
                            class="material-icons">keyboard_arrow_down</i></a>
                        <ul class="dropdown-menu" aria-labelledby="interne-tools-menu">
                          <li><a href="https://toledo.kuleuven.be/">Toledo</a></li>
                          <li><a href="https://admin.kuleuven.be/intranet/">Intranet</a></li>
                          <li><a href="https://webmail.kuleuven.be/">Webmail</a></li>
                          <li><a href="https://www.kuleuven.be/sapredir/kuloket">KU&nbsp;Loket</a></li>
                          <li><a href="https://www.kuleuven.be/wieiswie">Wie-is-wie</a></li>
                        </ul>
                    </li>
                    <li><a href="https://www.kuleuven-kulak.be/nl/ku-leuven-kulak">Nieuws</a>
                    </li>
                    <li><a href="https://www.kuleuven-kulak.be/nl/bibliotheek/">Bibliotheek</a>
                    </li>
                    <li><a href="https://www.kuleuven-kulak.be/nl/over-kulak/contact">Contact</a>
                    </li>
                    <li><a href="https://www.kuleuven.be/">KU&nbsp;Leuven</a></li>
                </ul>
            </nav>
        </div>
    </div>
</nav>
<!-- END GLOBAL HEADER -->
