<footer class="global-footer noindex hosted-by hidden-print d-print-none">
  <div class="footer-navbar">
    <div class="container">
      <div class="row">
      </div>
      
    </div>
  </div>
  
  <div class="bottom-footer">
    <div class="container">
      <div class="row">
        <div class="col legal">
          <a href="https://www.kuleuven.be/english" class="logo" title="KU Leuven">
            <img class="logo-img" alt="logo" src="" width="157" height="88">
          </a>
          <ul>
            <li> &copy; </li>
            <li><a href=""></a></li>
            <li><a href=""></a></li>
          </ul>
        </div>
        <div class="col">
        <div class="share">
          <span></span>
        </div>        </div>
      </div>
    </div>
  </div>
</footer>