<nav class="global-header noindex hidden-print">
  <div class="container">
    <a class="navbar-brand" href="https://www.kuleuven-kulak.be/en">
    <img class="logo" alt="logo" src="https://stijl.kuleuven.be/releases/latest/img/svg/logo.svg" width="157" height="56"/></a>
    <div class="controls">
      <form class="form-search hidden-md-down" role="search" action="" method="get" name="searchform">
        <input type="text" class="form-control" placeholder="" name="k" id="words">
        <button type="submit" class="btn btn-primary">
          <i class="material-icons">search</i>
        </button>
      </form>
      <a href="#" class="btn-toggle hidden-md-down" role="button"
         aria-expanded="false"
         aria-controls="kuleuven-menu"
         data-toggle="collapse" data-target="#kuleuven-menu">Info
         <span class="lines"></span>
      </a>
         
      <a href="#"
         class="btn-toggle hidden-lg-up js-flyout-toggle flyout-toggle collapsed"
         role="button" aria-expanded="false"
         aria-controls="flyout-menu"
         data-toggle="collapse" data-target="#flyout-menu">Info
         <span class="arrow"></span>
      </a>
    </div>
  </div>

  <div class="container hidden-md-down">
    <div class="nav navbar-nav navbar-collapse collapse" id="kuleuven-menu" role="navigation" aria-expanded="false">
      <nav class="nav-main pull-lg-left">
        <ul>
            <li><a href="https://www.kuleuven-kulak.be/en/research/">Research</a></li>
            <li><a href="https://www.kuleuven-kulak.be/en/education/">Education</a></li>
            <li><a href="https://www.kuleuven-kulak.be/en/about-kulak/">About KULAK</a></li>
        </ul>      </nav>
    </div>
  </div>
</nav>