name: test
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: /home/runner/work/web2020/

env:
  DEBUG: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: NPM install
        run: npm install
      
      - name: Static build
        env:
          BUILD: static
        run: npm run build

      - name: KUL CSS
        env:
          BUILD: css
        run: npm run build

      - name: KUL includes
        env:
          BUILD: includes
        run: npm run build

  


