name: test
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  DEBUG: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: NPM install
        working-directory: ${{ github.workspace }}
        run: npm install
      
      - name: Static build
        working-directory: ${{ github.workspace }}
        run: npm run build:static

  


