name: test
on:
  push:
    branches:
      - master

env:
  DEBUG: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: NPM install
        run: npm install
      
      - name: Static build
        env:
          BUILD: static
        run: npm run build

      - name: KUL CSS
        env:
          BUILD: css
        run: npm run build

      - name: KUL includes
        env:
          BUILD: includes
        run: npm run build

  


